# Generated by Django 5.1.4 on 2025-03-11 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_finaltokens'),
    ]

    operations = [
        migrations.RenameField(
            model_name='finaltokens',
            old_name='tokens',
            new_name='token',
        ),
    ]
