# Generated by Django 5.1.4 on 2025-03-11 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_rename_tokens_finaltokens_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='api_key',
        ),
        migrations.RemoveField(
            model_name='store',
            name='location',
        ),
        migrations.RemoveField(
            model_name='store',
            name='user',
        ),
        migrations.RemoveField(
            model_name='userlocation',
            name='token',
        ),
        migrations.RemoveField(
            model_name='userlocation',
            name='user',
        ),
        migrations.AddField(
            model_name='store',
            name='Address',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='latitude',
            field=models.CharField(default='0.0', max_length=255),
        ),
        migrations.AddField(
            model_name='store',
            name='longitude',
            field=models.CharField(default='0.0', max_length=255),
        ),
        migrations.AddField(
            model_name='userlocation',
            name='latitude',
            field=models.CharField(default='0.0', max_length=30),
        ),
        migrations.AddField(
            model_name='userlocation',
            name='longitude',
            field=models.CharField(default='0.0', max_length=30),
        ),
        migrations.AlterField(
            model_name='store',
            name='store_name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
