# Generated by Django 5.1.4 on 2025-03-12 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0012_rename_address_store_address_product_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.URLField(blank=True, default='http://example.com/default-image.jpg', null=True),
        ),
    ]
